### ISSUE TITLE
what's wrong?

### ISSUE THREAD

**Issue by nihaitao1325** [AndrewFreemantle/OSPhoto#4]
![QQ截图20241102132914](https://github.com/user-attachments/assets/cc07bd88-de2d-40f0-8b68-e3a6fd338308)
![QQ截图20241102132822](https://github.com/user-attachments/assets/b7ee284a-745a-4383-837f-acdda030f488)

**Comment by AndrewFreemantle** [comment]
@nihaitao1325 嗨，感谢您提出问题 🙂

目前，该项目为群晖的移动应用程序提供了一个API，但没有您的相册的网页视图。这些应用可以在这里找到：
Google Android: https://play.google.com/store/apps/details?id=com.synology.dsphoto
Apple iOS: https://itunes.apple.com/app/ds-photo/id321493106

**Comment by AndrewFreemantle** [comment]
@nihaitao1325 嗨，感谢您提出问题 🙂

目前，该项目为群晖的移动应用程序提供了一个API，但没有您的相册的网页视图。这些应用可以在这里找到：

At the moment this project provides an API for Synology's mobile apps, and does not have a web view of your photo album. The apps can be found here:

Google Android: https://play.google.com/store/apps/details?id=com.synology.dsphoto
Apple iOS: https://itunes.apple.com/app/ds-photo/id321493106
